### ISSUE TITLE
LED Brightness

### ISSUE THREAD

**Issue by Processedkid** [andydoro/IMA767_MEDP349_Spring2019#1]
Hi guys! I was wondering if anyone figured out how to make the LED lights brighter. I did some searching on the web but nothing they said worked. I have my lights setup where they delay and look like Knightrider but I can't figure out the brightness level. Any info would help! Thanks!

**Comment by kkaila777** [comment]
Did you use a power supply greater than 5V?

**Comment by jameskeogh** [comment]
I'm curious as to what ohms the resistors you used are. If my understanding is correct, using a higher number results in greater resistance, so your lights will be dimmer. I think it's something physical, not your code. The CIRC01 tutorial asked for 560, but I had to use 220.

**Comment by andydoro** [comment]
@jameskeogh is on the right track- lower value resistors will let more current flow to the LED, making them brighter. This has to do with Ohm's Law. Also note, different LEDs may have different electrical characteristics and thus will work better with different resistor values.
