### ISSUE TITLE
What are some better ways to store the resistors?

### ISSUE THREAD

**Issue by rxnaij** [andydoro/IMA767_MEDP349_Spring2019#3]
Hey all! I got the Elegoo UNO R3 Super Starter Kit and the resistors come attached to two really flimsy pieces of paper. It's a pain in the butt putting the resistors back into those pieces, especially after they get real bent up from use.

I'm wondering: what are some more practical ways to organize the resistors, while also saving space? The kit box isn't very big so I'm afraid that getting separate bags for all of them will take up too much space.

**Comment by kkaila777** [comment]
I just threw mine back in the bag with the resistors that were unused. They're all in the space spot in this way. Seems to be working fine so far.
