### ISSUE TITLE
Common Cathode vs. Common Anode

### ISSUE THREAD

**Issue by kkaila777** [andydoro/IMA767_MEDP349_Spring2019#4]
I programmed a 4 digit 7 segment display. In my code, when doing the digitalWrite for the digits, LOW would turn that digit on. When doing the digitalWrite for the segments, HIGH would turn that segment on. Does this mean I am working with a common anode or cathode? #confused 

Example:
digitalWrite(D1, LOW);
digitalWrite(D2, HIGH);
digitalWrite(D3, HIGH);
digitalWrite(D4, HIGH);
//my first digit will be 0, turning off G segment to make 0 
//on LED display
digitalWrite(pinA, HIGH);
digitalWrite(pinB, HIGH);
digitalWrite(pinC, HIGH);
digitalWrite(pinD, HIGH);
digitalWrite(pinE, HIGH);
digitalWrite(pinF, HIGH);
digitalWrite(pinG, LOW);
delay(500);

**Comment by andydoro** [comment]
the mnemonic for "anode" vs. "cathode" is "ACID - Anode: Current Into Device". Common anode in this case means you power the device through a single pin (the anode) then light up the segments by bringing the other pins LOW. This is the most common configuration for devices like this (e.g. RGB LEDs are usually common anode. Common cathode is much more rare.)

**Comment by kkaila777** [comment]
Ah okay thank you. By the way, I put up the links for both of my videos. They took a while to upload. It's in my homework post. See you later, thanks again.
