### ISSUE TITLE
Issues with capacitive touch and alligator clips with CPX

### ISSUE THREAD

**Issue by jameskeogh** [andydoro/IMA767_MEDP349_Spring2019#7]
I'm attempting to use capacitive touch to activate tones on the Circut Python Express. I've had success with using two different codes ([Make Code .uf2 file](https://core-electronics.com.au/tutorials/capacitive-touch-keyboard-makecode-adafruit-circuit-playground-express-tutorial.html) and [CircutPython .py file](https://learn.adafruit.com/circuit-playground-express-piano-in-the-key-of-lime?view=all), both based on what they're linked to) and when the pin on the board is touched, I get sound.

However, whenever I attach an alligator clip, there's continual contact that keeps triggering the sound. I've experimented with code that should have solved this problem and I know there's the mute switch, but nothing is working.

I'm assuming something I'm doing/overlooking is the variable, but I haven't figured it out yet.

**Comment by andydoro** [comment]
That's odd, according to [this tutorial](https://learn.adafruit.com/circuitpython-made-easy-on-circuit-playground-express/capacitive-touch) alligator clips should be fine. 

One thing I found is this note:  "The capacitive touch pads calibrate on startup, so if you leave your CPX powered on, you may need to hit the reset button after attaching the fruit." from [Piano in the Key of Lime](https://learn.adafruit.com/circuit-playground-express-piano-in-the-key-of-lime/piano-in-the-key-of-lime)

**Comment by jameskeogh** [comment]
I tried the reset last night and it didn't work, but seems to be functional today. I do have to reset after every clip is attached, which I didn't do yesterday.
